// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(MCF_DavinContext))]
    [Migration("20241129005928_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend.Models.MsStorageLocation", b =>
                {
                    b.Property<string>("LocationId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location_name");

                    b.HasKey("LocationId")
                        .HasName("PK__ms_stora__771831EA8B61A42D");

                    b.ToTable("ms_storage_location", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MsUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("PK__ms_user__B9BE370F9187C927");

                    b.ToTable("ms_user", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TrBpkb", b =>
                {
                    b.Property<string>("AgreementNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("agreement_number");

                    b.Property<DateTime?>("BpkbDate")
                        .HasColumnType("datetime")
                        .HasColumnName("bpkb_date");

                    b.Property<DateTime?>("BpkbDateIn")
                        .HasColumnType("datetime")
                        .HasColumnName("bpkb_date_in");

                    b.Property<string>("BpkbNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bpkb_no");

                    b.Property<string>("BranchId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("branch_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("FakturDate")
                        .HasColumnType("datetime")
                        .HasColumnName("faktur_date");

                    b.Property<string>("FakturNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("faktur_no");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("last_updated_by");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated_on");

                    b.Property<string>("LocationId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<string>("PoliceNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("police_no");

                    b.HasKey("AgreementNumber")
                        .HasName("PK__tr_bpkb__21912C808EF894A5");

                    b.HasIndex("LocationId");

                    b.ToTable("tr_bpkb", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TrBpkb", b =>
                {
                    b.HasOne("Backend.Models.MsStorageLocation", "Location")
                        .WithMany("TrBpkbs")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__tr_bpkb__locatio__286302EC");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Backend.Models.MsStorageLocation", b =>
                {
                    b.Navigation("TrBpkbs");
                });
#pragma warning restore 612, 618
        }
    }
}
